import Tshirts from "../assets/Images/tshirts.jpg";
import Building from "../assets/Images/building.jpg";
import Mountain from "../assets/Images/mountain.jpg";
import Flowers from "../assets/Images/flowers.jpg";
import WhiteFigure from "../assets/Images/whiteFigure.jpg";
import HagiSophia from "../assets/Images/hagiaSophia.jpg";
import Sea from "../assets/Images/sea.jpg";

export let perfumesObj = {
  Bestseller: [
    {
      name: "Blanche parfum",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Tuscan Creations",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Terra Rossa",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Glorious Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "The Alchemist",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Garden A Winter",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Melody Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Toilette",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
  ],
  "New Arrivals": [
    {
      name: "Blanche parfum 1",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Tuscan Creations",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Terra Rossa",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Glorious Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "The Alchemist",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Garden A Winter",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Melody Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Toilette",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
  ],
  "Top Rated": [
    {
      name: "Blanche parfum",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Tuscan Creations",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Terra Rossa",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Glorious Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "The Alchemist",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Garden A Winter",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Melody Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Toilette",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
  ],
} as any;

export let imageArr = [
  Tshirts,
  Building,
  Mountain,
  Flowers,
  WhiteFigure,
  HagiSophia,
  Sea,
] as any;
