import Tshirts from "../assets/Images/tshirts.jpg";
import Building from "../assets/Images/building.jpg";
import Mountain from "../assets/Images/mountain.jpg";
import Flowers from "../assets/Images/flowers.jpg";
import WhiteFigure from "../assets/Images/whiteFigure.jpg";
import HagiSophia from "../assets/Images/hagiaSophia.jpg";
import Sea from "../assets/Images/sea.jpg";

export let perfumesObj = {
  Bestseller: [
    {
      name: "Blanche parfum",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Tuscan Creations",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Terra Rossa",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Glorious Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "The Alchemist",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Garden A Winter",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Melody Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Toilette",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
  ],
  "New Arrivals": [
    {
      name: "Blanche parfum 1",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Tuscan Creations",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Terra Rossa",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Glorious Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "The Alchemist",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Garden A Winter",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Melody Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Toilette",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
  ],
  "Top Rated": [
    {
      name: "Blanche parfum",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Tuscan Creations",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Terra Rossa",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Glorious Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "The Alchemist",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Garden A Winter",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Melody Eau",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
    {
      name: "Toilette",
      rating: 3,
      originalPrice: 65,
      discountedPrice: 45,
      availability: "In Stock",
      color: ["White", "Black", "Teal", "Brown"],
      colorCode: ["#dce0dd", "#000000", "#008080", "#A52A2A"],
      size: ["XS", "S", "M", "L", "XL", "XXL"],
    },
  ],
} as any;

export let dealOfTheDayObj = [
  {
    title: "Glorious Eau",
    images: [
      "https://pronk.in/cdn/shop/files/49_2e3b3e43-98fa-44eb-a06a-6c6c79a43ffa.jpg?v=1708776622&width=1080",
      "https://pronk.in/cdn/shop/files/50_97e30b5b-69e9-4ad8-90a3-2afe8581eb0a.jpg?v=1708776621&width=1080",
      "https://pronk.in/cdn/shop/files/51_e705bd37-d543-4234-80fe-fd7cee4bc9be.jpg?v=1708776622&width=1080",
      "https://pronk.in/cdn/shop/files/52_9c2a1904-550e-44b7-bd5a-c3664e524054.jpg?v=1708776623&width=1080",
    ],
    price: 49,
  },
  {
    title: "Bibliotheque",
    images: [
      "https://pronk.in/cdn/shop/files/76_ffe7436b-8d57-4f93-bbe8-c4af85b00a69.jpg?v=1730726855&width=1080",
    ],
    price: 49,
  },
  {
    title: "Dunas De Un",
    images: [
      "https://cdn.pixabay.com/photo/2024/04/29/04/21/tshirt-8726721_1280.jpg",
    ],
    price: 49,
  },
  {
    title: "Cuerpo Eau",
    images: [
      "https://cdn.pixabay.com/photo/2023/05/08/21/59/tshirt-7979853_1280.jpg",
    ],
    price: 49,
  },
  {
    title: "Additional Product",
    images: [
      "https://cdn.pixabay.com/photo/2024/04/17/18/40/ai-generated-8702729_1280.jpg",
    ],
    price: 49,
  },
  {
    title: "Additional Product",
    images: [
      "https://plus.unsplash.com/premium_photo-1675186049366-64a655f8f537?q=80&w=3087&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    ],
    price: 49,
  },
  {
    title: "Additional Product",
    images: [
      "https://images.unsplash.com/photo-1523205565295-f8e91625443b?w=900&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8ODB8c29jQWF1YXVsUEl8fGVufDB8fHx8fA%3D%3D",
    ],
    price: 49,
  },
];

export let imageArr = [
  Tshirts,
  Building,
  Mountain,
  Flowers,
  WhiteFigure,
  HagiSophia,
  Sea,
] as any;
